Progressive reward callback (#22)
* Support for multiple callbacks to be passed into learn

* MicrortsRewardDecayCallback decays all rewards except WinLoss

* Only eval every 1M steps because it's incredibly expensive

* Want element multiplication, not dot product

* Fix undefined reference to callback